export interface Vowel {
  id: string;
  symbol: string;
  name: string;
  arabicName: string;
}

export interface Letter {
  id: string;
  char: string; // Initial form
  // name: string;
}

export interface Syllable {
  letterId: string;
  vowelId: string;
  result: string;
  audioPath?: string;
}

export const VOWELS: Vowel[] = [
  { id: "none", symbol: " ", name: "None", arabicName: "بدون حركة" },
  { id: "fatha", symbol: "◌َ", name: "Fatha", arabicName: "فتحة" },
  { id: "damma", symbol: "◌ُ", name: "Damma", arabicName: "ضمة" },
  { id: "kasra", symbol: "◌ِ", name: "Kasra", arabicName: "كسرة" },
  { id: "alif", symbol: "ا", name: "Alif", arabicName: "مد بالألف" },
  { id: "waw", symbol: "و", name: "Waw", arabicName: "مد بالواو" },
  { id: "ya", symbol: "ي", name: "Ya", arabicName: "مد بالياء" },
  { id: "fathatayn", symbol: "◌ً", name: "Fathatayn", arabicName: "تنوين بالفتح" },
  { id: "dammatayn", symbol: "◌ٌ", name: "Dammatayn", arabicName: "تنوين بالضم" },
  { id: "kasratayn", symbol: "◌ٍ", name: "Kasratayn", arabicName: "تنوين بالكسر" },
];

export const LETTERS: Letter[] = [
  { id: "alif", char: "أ"},
  { id: "ba", char: "بـ"},
  { id: "ta", char: "تـ"},
  { id: "tha", char: "ثـ"},
  { id: "jeem", char: "جـ"},
  { id: "haa", char: "حـ"},
  { id: "khaa", char: "خـ"},
  { id: "dal", char: "د"},
  { id: "dhal", char: "ذ"},
  { id: "ra", char: "ر"},
  { id: "zay", char: "ز"},
  { id: "seen", char: "سـ"},
  { id: "sheen", char: "شـ"},
  { id: "sad", char: "صـ"},
  { id: "dad", char: "ضـ"},
  { id: "ttaa", char: "طـ"},
  { id: "dhaa", char: "ظـ"},
  { id: "ayn", char: "عـ"},
  { id: "ghayn", char: "غـ"},
  { id: "fa", char: "فـ"},
  { id: "qaf", char: "قـ"},
  { id: "kaf", char: "كـ"},
  { id: "lam", char: "لـ"},
  { id: "meem", char: "مـ"},
  { id: "noon", char: "نـ"},
  { id: "ha", char: "هـ"},
  { id: "waw", char: "و"},
  { id: "ya", char: "يـ"},
];

export const SYLLABLES: Syllable[] = [
  // Alif
  { letterId: "alif", vowelId: "fatha", result: "أَ" },
  { letterId: "alif", vowelId: "damma", result: "أُ" },
  { letterId: "alif", vowelId: "kasra", result: "إِ" },
  { letterId: "alif", vowelId: "fathatayn", result: "أً" },
  { letterId: "alif", vowelId: "dammatayn", result: "أٌ" },
  { letterId: "alif", vowelId: "kasratayn", result: "إٍ" },
  { letterId: "alif", vowelId: "alif", result: "آ" },
  { letterId: "alif", vowelId: "waw", result: "أو" },
  { letterId: "alif", vowelId: "ya", result: "أي" },
  // Ba
  { letterId: "ba", vowelId: "fatha", result: "بَ" },
  { letterId: "ba", vowelId: "damma", result: "بُ" },
  { letterId: "ba", vowelId: "kasra", result: "بِ" },
  { letterId: "ba", vowelId: "fathatayn", result: "بًا" },
  { letterId: "ba", vowelId: "dammatayn", result: "بٌ" },
  { letterId: "ba", vowelId: "kasratayn", result: "بٍ" },
  { letterId: "ba", vowelId: "alif", result: "با" },
  { letterId: "ba", vowelId: "waw", result: "بو" },
  { letterId: "ba", vowelId: "ya", result: "بي" },
  // Ta
  { letterId: "ta", vowelId: "fatha", result: "تَ" },
  { letterId: "ta", vowelId: "damma", result: "تُ" },
  { letterId: "ta", vowelId: "kasra", result: "تِ" },
  { letterId: "ta", vowelId: "fathatayn", result: "تًا" },
  { letterId: "ta", vowelId: "dammatayn", result: "تٌ" },
  { letterId: "ta", vowelId: "kasratayn", result: "تٍ" },
  { letterId: "ta", vowelId: "alif", result: "تا" },
  { letterId: "ta", vowelId: "waw", result: "تو" },
  { letterId: "ta", vowelId: "ya", result: "تي" },
  // Tha
  { letterId: "tha", vowelId: "fatha", result: "ثَ" },
  { letterId: "tha", vowelId: "damma", result: "ثُ" },
  { letterId: "tha", vowelId: "kasra", result: "ثِ" },
  { letterId: "tha", vowelId: "fathatayn", result: "ثًا" },
  { letterId: "tha", vowelId: "dammatayn", result: "ثٌ" },
  { letterId: "tha", vowelId: "kasratayn", result: "ثٍ" },
  { letterId: "tha", vowelId: "alif", result: "ثا" },
  { letterId: "tha", vowelId: "waw", result: "ثو" },
  { letterId: "tha", vowelId: "ya", result: "ثي" },
  // Jeem
  { letterId: "jeem", vowelId: "fatha", result: "جَ" },
  { letterId: "jeem", vowelId: "damma", result: "جُ" },
  { letterId: "jeem", vowelId: "kasra", result: "جِ" },
  { letterId: "jeem", vowelId: "fathatayn", result: "جًا" },
  { letterId: "jeem", vowelId: "dammatayn", result: "جٌ" },
  { letterId: "jeem", vowelId: "kasratayn", result: "جٍ" },
  { letterId: "jeem", vowelId: "alif", result: "جا" },
  { letterId: "jeem", vowelId: "waw", result: "جو" },
  { letterId: "jeem", vowelId: "ya", result: "جي" },
  // Haa
  { letterId: "haa", vowelId: "fatha", result: "حَ" },
  { letterId: "haa", vowelId: "damma", result: "حُ" },
  { letterId: "haa", vowelId: "kasra", result: "حِ" },
  { letterId: "haa", vowelId: "fathatayn", result: "حًا" },
  { letterId: "haa", vowelId: "dammatayn", result: "حٌ" },
  { letterId: "haa", vowelId: "kasratayn", result: "حٍ" },
  { letterId: "haa", vowelId: "alif", result: "حا" },
  { letterId: "haa", vowelId: "waw", result: "حو" },
  { letterId: "haa", vowelId: "ya", result: "حي" },
  // Khaa
  { letterId: "khaa", vowelId: "fatha", result: "خَ" },
  { letterId: "khaa", vowelId: "damma", result: "خُ" },
  { letterId: "khaa", vowelId: "kasra", result: "خِ" },
  { letterId: "khaa", vowelId: "fathatayn", result: "خًا" },
  { letterId: "khaa", vowelId: "dammatayn", result: "خٌ" },
  { letterId: "khaa", vowelId: "kasratayn", result: "خٍ" },
  { letterId: "khaa", vowelId: "alif", result: "خا" },
  { letterId: "khaa", vowelId: "waw", result: "خو" },
  { letterId: "khaa", vowelId: "ya", result: "خي" },
  // Dal
  { letterId: "dal", vowelId: "fatha", result: "دَ" },
  { letterId: "dal", vowelId: "damma", result: "دُ" },
  { letterId: "dal", vowelId: "kasra", result: "دِ" },
  { letterId: "dal", vowelId: "fathatayn", result: "دًا" },
  { letterId: "dal", vowelId: "dammatayn", result: "دٌ" },
  { letterId: "dal", vowelId: "kasratayn", result: "دٍ" },
  { letterId: "dal", vowelId: "alif", result: "دا" },
  { letterId: "dal", vowelId: "waw", result: "دو" },
  { letterId: "dal", vowelId: "ya", result: "دي" },
  // Dhal
  { letterId: "dhal", vowelId: "fatha", result: "ذَ" },
  { letterId: "dhal", vowelId: "damma", result: "ذُ" },
  { letterId: "dhal", vowelId: "kasra", result: "ذِ" },
  { letterId: "dhal", vowelId: "fathatayn", result: "ذًا" },
  { letterId: "dhal", vowelId: "dammatayn", result: "ذٌ" },
  { letterId: "dhal", vowelId: "kasratayn", result: "ذٍ" },
  { letterId: "dhal", vowelId: "alif", result: "ذا" },
  { letterId: "dhal", vowelId: "waw", result: "ذو" },
  { letterId: "dhal", vowelId: "ya", result: "ذي" },
  // Ra
  { letterId: "ra", vowelId: "fatha", result: "رَ" },
  { letterId: "ra", vowelId: "damma", result: "رُ" },
  { letterId: "ra", vowelId: "kasra", result: "رِ" },
  { letterId: "ra", vowelId: "fathatayn", result: "رًا" },
  { letterId: "ra", vowelId: "dammatayn", result: "رٌ" },
  { letterId: "ra", vowelId: "kasratayn", result: "رٍ" },
  { letterId: "ra", vowelId: "alif", result: "را" },
  { letterId: "ra", vowelId: "waw", result: "رو" },
  { letterId: "ra", vowelId: "ya", result: "ري" },
  // Zay
  { letterId: "zay", vowelId: "fatha", result: "زَ" },
  { letterId: "zay", vowelId: "damma", result: "زُ" },
  { letterId: "zay", vowelId: "kasra", result: "زِ" },
  { letterId: "zay", vowelId: "fathatayn", result: "زًا" },
  { letterId: "zay", vowelId: "dammatayn", result: "زٌ" },
  { letterId: "zay", vowelId: "kasratayn", result: "زٍ" },
  { letterId: "zay", vowelId: "alif", result: "زا" },
  { letterId: "zay", vowelId: "waw", result: "زو" },
  { letterId: "zay", vowelId: "ya", result: "زي" },
  // Seen
  { letterId: "seen", vowelId: "fatha", result: "سَ" },
  { letterId: "seen", vowelId: "damma", result: "سُ" },
  { letterId: "seen", vowelId: "kasra", result: "سِ" },
  { letterId: "seen", vowelId: "fathatayn", result: "سًا" },
  { letterId: "seen", vowelId: "dammatayn", result: "سٌ" },
  { letterId: "seen", vowelId: "kasratayn", result: "سٍ" },
  { letterId: "seen", vowelId: "alif", result: "سا" },
  { letterId: "seen", vowelId: "waw", result: "سو" },
  { letterId: "seen", vowelId: "ya", result: "سي" },
  // Sheen
  { letterId: "sheen", vowelId: "fatha", result: "شَ" },
  { letterId: "sheen", vowelId: "damma", result: "شُ" },
  { letterId: "sheen", vowelId: "kasra", result: "شِ" },
  { letterId: "sheen", vowelId: "fathatayn", result: "شًا" },
  { letterId: "sheen", vowelId: "dammatayn", result: "شٌ" },
  { letterId: "sheen", vowelId: "kasratayn", result: "شٍ" },
  { letterId: "sheen", vowelId: "alif", result: "شا" },
  { letterId: "sheen", vowelId: "waw", result: "شو" },
  { letterId: "sheen", vowelId: "ya", result: "شي" },
  // Sad
  { letterId: "sad", vowelId: "fatha", result: "صَ" },
  { letterId: "sad", vowelId: "damma", result: "صُ" },
  { letterId: "sad", vowelId: "kasra", result: "صِ" },
  { letterId: "sad", vowelId: "fathatayn", result: "صًا" },
  { letterId: "sad", vowelId: "dammatayn", result: "صٌ" },
  { letterId: "sad", vowelId: "kasratayn", result: "صٍ" },
  { letterId: "sad", vowelId: "alif", result: "صا" },
  { letterId: "sad", vowelId: "waw", result: "صو" },
  { letterId: "sad", vowelId: "ya", result: "صي" },
  // Dad
  { letterId: "dad", vowelId: "fatha", result: "ضَ" },
  { letterId: "dad", vowelId: "damma", result: "ضُ" },
  { letterId: "dad", vowelId: "kasra", result: "ضِ" },
  { letterId: "dad", vowelId: "fathatayn", result: "ضًا" },
  { letterId: "dad", vowelId: "dammatayn", result: "ضٌ" },
  { letterId: "dad", vowelId: "kasratayn", result: "ضٍ" },
  { letterId: "dad", vowelId: "alif", result: "ضا" },
  { letterId: "dad", vowelId: "waw", result: "ضو" },
  { letterId: "dad", vowelId: "ya", result: "ضي" },
  // Ttaa
  { letterId: "ttaa", vowelId: "fatha", result: "طَ" },
  { letterId: "ttaa", vowelId: "damma", result: "طُ" },
  { letterId: "ttaa", vowelId: "kasra", result: "طِ" },
  { letterId: "ttaa", vowelId: "fathatayn", result: "طًا" },
  { letterId: "ttaa", vowelId: "dammatayn", result: "طٌ" },
  { letterId: "ttaa", vowelId: "kasratayn", result: "طٍ" },
  { letterId: "ttaa", vowelId: "alif", result: "طا" },
  { letterId: "ttaa", vowelId: "waw", result: "طو" },
  { letterId: "ttaa", vowelId: "ya", result: "طي" },
  // Dhaa
  { letterId: "dhaa", vowelId: "fatha", result: "ظَ" },
  { letterId: "dhaa", vowelId: "damma", result: "ظُ" },
  { letterId: "dhaa", vowelId: "kasra", result: "ظِ" },
  { letterId: "dhaa", vowelId: "fathatayn", result: "ظًا" },
  { letterId: "dhaa", vowelId: "dammatayn", result: "ظٌ" },
  { letterId: "dhaa", vowelId: "kasratayn", result: "ظٍ" },
  { letterId: "dhaa", vowelId: "alif", result: "ظا" },
  { letterId: "dhaa", vowelId: "waw", result: "ظو" },
  { letterId: "dhaa", vowelId: "ya", result: "ظي" },
  // Ayn
  { letterId: "ayn", vowelId: "fatha", result: "عَ" },
  { letterId: "ayn", vowelId: "damma", result: "عُ" },
  { letterId: "ayn", vowelId: "kasra", result: "عِ" },
  { letterId: "ayn", vowelId: "fathatayn", result: "عًا" },
  { letterId: "ayn", vowelId: "dammatayn", result: "عٌ" },
  { letterId: "ayn", vowelId: "kasratayn", result: "عٍ" },
  { letterId: "ayn", vowelId: "alif", result: "عا" },
  { letterId: "ayn", vowelId: "waw", result: "عو" },
  { letterId: "ayn", vowelId: "ya", result: "عي" },
  // Ghayn
  { letterId: "ghayn", vowelId: "fatha", result: "غَ" },
  { letterId: "ghayn", vowelId: "damma", result: "غُ" },
  { letterId: "ghayn", vowelId: "kasra", result: "غِ" },
  { letterId: "ghayn", vowelId: "fathatayn", result: "غًا" },
  { letterId: "ghayn", vowelId: "dammatayn", result: "غٌ" },
  { letterId: "ghayn", vowelId: "kasratayn", result: "غٍ" },
  { letterId: "ghayn", vowelId: "alif", result: "غا" },
  { letterId: "ghayn", vowelId: "waw", result: "غو" },
  { letterId: "ghayn", vowelId: "ya", result: "غي" },
  // Fa
  { letterId: "fa", vowelId: "fatha", result: "فَ" },
  { letterId: "fa", vowelId: "damma", result: "فُ" },
  { letterId: "fa", vowelId: "kasra", result: "فِ" },
  { letterId: "fa", vowelId: "fathatayn", result: "فًا" },
  { letterId: "fa", vowelId: "dammatayn", result: "فٌ" },
  { letterId: "fa", vowelId: "kasratayn", result: "فٍ" },
  { letterId: "fa", vowelId: "alif", result: "فا" },
  { letterId: "fa", vowelId: "waw", result: "فو" },
  { letterId: "fa", vowelId: "ya", result: "في" },
  // Qaf
  { letterId: "qaf", vowelId: "fatha", result: "قَ" },
  { letterId: "qaf", vowelId: "damma", result: "قُ" },
  { letterId: "qaf", vowelId: "kasra", result: "قِ" },
  { letterId: "qaf", vowelId: "fathatayn", result: "قًا" },
  { letterId: "qaf", vowelId: "dammatayn", result: "قٌ" },
  { letterId: "qaf", vowelId: "kasratayn", result: "قٍ" },
  { letterId: "qaf", vowelId: "alif", result: "قا" },
  { letterId: "qaf", vowelId: "waw", result: "قو" },
  { letterId: "qaf", vowelId: "ya", result: "قي" },
  // Kaf
  { letterId: "kaf", vowelId: "fatha", result: "كَ" },
  { letterId: "kaf", vowelId: "damma", result: "كُ" },
  { letterId: "kaf", vowelId: "kasra", result: "كِ" },
  { letterId: "kaf", vowelId: "fathatayn", result: "كًا" },
  { letterId: "kaf", vowelId: "dammatayn", result: "كٌ" },
  { letterId: "kaf", vowelId: "kasratayn", result: "كٍ" },
  { letterId: "kaf", vowelId: "alif", result: "كا" },
  { letterId: "kaf", vowelId: "waw", result: "كو" },
  { letterId: "kaf", vowelId: "ya", result: "كي" },
  // Lam
  { letterId: "lam", vowelId: "fatha", result: "لَ" },
  { letterId: "lam", vowelId: "damma", result: "لُ" },
  { letterId: "lam", vowelId: "kasra", result: "لِ" },
  { letterId: "lam", vowelId: "fathatayn", result: "لًا" },
  { letterId: "lam", vowelId: "dammatayn", result: "لٌ" },
  { letterId: "lam", vowelId: "kasratayn", result: "لٍ" },
  { letterId: "lam", vowelId: "alif", result: "لا" },
  { letterId: "lam", vowelId: "waw", result: "لو" },
  { letterId: "lam", vowelId: "ya", result: "لي" },
  // Meem
  { letterId: "meem", vowelId: "fatha", result: "مَ" },
  { letterId: "meem", vowelId: "damma", result: "مُ" },
  { letterId: "meem", vowelId: "kasra", result: "مِ" },
  { letterId: "meem", vowelId: "fathatayn", result: "مًا" },
  { letterId: "meem", vowelId: "dammatayn", result: "مٌ" },
  { letterId: "meem", vowelId: "kasratayn", result: "مٍ" },
  { letterId: "meem", vowelId: "alif", result: "ما" },
  { letterId: "meem", vowelId: "waw", result: "مو" },
  { letterId: "meem", vowelId: "ya", result: "مي" },
  // Noon
  { letterId: "noon", vowelId: "fatha", result: "نَ" },
  { letterId: "noon", vowelId: "damma", result: "نُ" },
  { letterId: "noon", vowelId: "kasra", result: "نِ" },
  { letterId: "noon", vowelId: "fathatayn", result: "نًا" },
  { letterId: "noon", vowelId: "dammatayn", result: "نٌ" },
  { letterId: "noon", vowelId: "kasratayn", result: "نٍ" },
  { letterId: "noon", vowelId: "alif", result: "نا" },
  { letterId: "noon", vowelId: "waw", result: "نو" },
  { letterId: "noon", vowelId: "ya", result: "ني" },
  // Ha
  { letterId: "ha", vowelId: "fatha", result: "هَ" },
  { letterId: "ha", vowelId: "damma", result: "هُ" },
  { letterId: "ha", vowelId: "kasra", result: "هِ" },
  { letterId: "ha", vowelId: "fathatayn", result: "هًا" },
  { letterId: "ha", vowelId: "dammatayn", result: "هٌ" },
  { letterId: "ha", vowelId: "kasratayn", result: "هٍ" },
  { letterId: "ha", vowelId: "alif", result: "ها" },
  { letterId: "ha", vowelId: "waw", result: "هو" },
  { letterId: "ha", vowelId: "ya", result: "هي" },
  // Waw
  { letterId: "waw", vowelId: "fatha", result: "وَ" },
  { letterId: "waw", vowelId: "damma", result: "وُ" },
  { letterId: "waw", vowelId: "kasra", result: "وِ" },
  { letterId: "waw", vowelId: "fathatayn", result: "وًا" },
  { letterId: "waw", vowelId: "dammatayn", result: "وٌ" },
  { letterId: "waw", vowelId: "kasratayn", result: "وٍ" },
  { letterId: "waw", vowelId: "alif", result: "وا" },
  { letterId: "waw", vowelId: "waw", result: "وو" },
  { letterId: "waw", vowelId: "ya", result: "وي" },
  // Ya
  { letterId: "ya", vowelId: "fatha", result: "يَ" },
  { letterId: "ya", vowelId: "damma", result: "يُ" },
  { letterId: "ya", vowelId: "kasra", result: "يِ" },
  { letterId: "ya", vowelId: "fathatayn", result: "يًا" },
  { letterId: "ya", vowelId: "dammatayn", result: "يٌ" },
  { letterId: "ya", vowelId: "kasratayn", result: "يٍ" },
  { letterId: "ya", vowelId: "alif", result: "يا" },
  { letterId: "ya", vowelId: "waw", result: "يو" },
  { letterId: "ya", vowelId: "ya", result: "يي" },
];
